export const strings = {
  app: {
    title: "Agrobank",
    subtitle: "Xodimlar monitoringi tizimi",
  },
  nav: {
    monitoring: "Monitoring",
    employees: "Xodimlar",
    referenceData: "Ma'lumotnoma",
    reports: "Hisobotlar",
  },
  auth: {
    tagline: "Xodimlaringiz joylashuvini real vaqtda kuzating",
    username: "Foydalanuvchi nomi",
    password: "Parol",
    usernamePlaceholder: "Foydalanuvchi nomini kiriting",
    passwordPlaceholder: "Parolni kiriting",
    submit: "Kirish",
    submitting: "Tekshirilmoqda...",
    trustLine: "Ma'lumotlaringiz himoyalangan",
    invalidCredentials: "Foydalanuvchi nomi yoki parol noto'g'ri",
    genericError: "Kirishda xatolik yuz berdi. Qayta urinib ko'ring",
    fieldRequired: "Bu maydon to'ldirilishi shart",
    logout: "Chiqish",
  },
  monitoring: {
    region: "Viloyat",
    regionPlaceholder: "Viloyatni tanlang",
    searchPlaceholder: "Xodimni qidirish",
    employeeListEmpty: "Ushbu viloyatda xodimlar topilmadi",
    searchEmpty: "Qidiruv bo'yicha xodim topilmadi",
    selectRegionFirst: "Xodimlarni ko'rish uchun avval viloyatni tanlang",
    loadingEmployees: "Xodimlar yuklanmoqda...",
    loadingRegions: "Viloyatlar yuklanmoqda...",
    date: "Sana",
    online: "Onlayn",
    offline: "Oflayn",
    loadingRoute: "Marshrut yuklanmoqda...",
    noRoute: "Ushbu sana uchun marshrut ma'lumotlari topilmadi",
    loadingStops: "To'xtash joylari yuklanmoqda...",
    noStops: "To'xtash joylari qayd etilmagan",
    retry: "Qayta urinish",
    errorLoading: "Ma'lumotlarni yuklashda xatolik yuz berdi",
    selectEmployeeHint: "Xaritada ko'rish uchun ro'yxatdan xodimni tanlang",
    live: "Jonli kuzatuv",
  },
  stopPopup: {
    address: "Manzil",
    arrival: "Kelgan vaqti",
    departure: "Ketgan vaqti",
    duration: "Davomiyligi",
    addressUnknown: "Manzil aniqlanmagan",
    stillHere: "Hozirgacha shu yerda",
  },
  employees: {
    pageTitle: "Xodimlar",
    pageSubtitle: "Xodimlar ro'yxati, tayinlash va faolsizlantirish",
    filtersRegion: "Viloyat",
    filtersRegionPlaceholder: "Barcha viloyatlar",
    filtersDistrict: "Tuman",
    filtersDistrictPlaceholder: "Barcha tumanlar",
    filtersDistrictDisabled: "Avval viloyatni tanlang",
    filtersDepartment: "Departament",
    filtersDepartmentPlaceholder: "Barcha departamentlar",
    filtersSearch: "Qidiruv",
    filtersSearchPlaceholder: "Xodim ismi bo'yicha qidirish",
    filtersReset: "Filtrlarni tozalash",
    columnName: "F.I.SH.",
    columnPhone: "Telefon raqami",
    columnRegion: "Viloyat",
    columnDistrict: "Tuman",
    columnDepartment: "Departament",
    columnPosition: "Lavozim",
    columnStatus: "Holati",
    columnActions: "Amallar",
    statusActive: "Faol",
    statusInactive: "Faolsiz",
    loading: "Xodimlar yuklanmoqda...",
    empty: "Xodimlar topilmadi",
    emptyHint: "Filtrlarni o'zgartirib ko'ring",
    searchEmpty: "Qidiruv bo'yicha xodim topilmadi",
    error: "Xodimlarni yuklashda xatolik yuz berdi",
    assign: "Tayinlash",
    deactivate: "Faolsizlantirish",
    assignModalTitle: "Xodimni tayinlash",
    assignDepartment: "Departament",
    assignDepartmentPlaceholder: "Departamentni tanlang",
    assignPosition: "Lavozim",
    assignPositionPlaceholder: "Lavozimni tanlang",
    assignRequired: "Bu maydon to'ldirilishi shart",
    assignSuccess: "Xodim muvaffaqiyatli tayinlandi",
    assignError: "Tayinlashda xatolik yuz berdi",
    deactivateTitle: "Xodimni faolsizlantirish",
    deactivateConfirm: "Ushbu xodimni faolsizlantirmoqchimisiz? Bu amalni bekor qilib bo'lmaydi.",
    deactivateOk: "Faolsizlantirish",
    deactivateCancel: "Bekor qilish",
    deactivateSuccess: "Xodim faolsizlantirildi",
    deactivateError: "Faolsizlantirishda xatolik yuz berdi",
    readOnlyNotice:
      "Xodimning ismi, telefon raqami, viloyati va tumani mobil ilova orqali boshqariladi va bu yerda tahrirlanmaydi.",
    notAssigned: "Tayinlanmagan",
    unknown: "Ma'lumot yo'q",
  },
  referenceData: {
    pageTitle: "Ma'lumotnoma",
    pageSubtitle: "Viloyatlar, tumanlar, departamentlar va lavozimlar",
    tabRegions: "Viloyatlar",
    tabDistricts: "Tumanlar",
    tabDepartments: "Departamentlar",
    tabPositions: "Lavozimlar",
    columnName: "Nomi",
    columnRegion: "Viloyat",
    columnLatitude: "Kenglik",
    columnLongitude: "Uzunlik",
    columnActions: "Amallar",
    add: "Qo'shish",
    edit: "Tahrirlash",
    remove: "O'chirish",
    save: "Saqlash",
    cancel: "Bekor qilish",
    nameLabel: "Nomi",
    namePlaceholder: "Nomini kiriting",
    latitudeLabel: "Kenglik",
    longitudeLabel: "Uzunlik",
    regionLabel: "Viloyat",
    regionPlaceholder: "Viloyatni tanlang",
    required: "Bu maydon to'ldirilishi shart",
    selectRegionFirst: "Tumanlarni ko'rish uchun avval viloyatni tanlang",
    loading: "Ma'lumotlar yuklanmoqda...",
    error: "Ma'lumotlarni yuklashda xatolik yuz berdi",
    emptyRegions: "Viloyatlar qo'shilmagan",
    emptyDistricts: "Ushbu viloyatda tumanlar qo'shilmagan",
    emptyDepartments: "Departamentlar qo'shilmagan",
    emptyPositions: "Lavozimlar qo'shilmagan",
    addRegion: "Yangi viloyat",
    editRegion: "Viloyatni tahrirlash",
    addDistrict: "Yangi tuman",
    editDistrict: "Tumanni tahrirlash",
    addDepartment: "Yangi departament",
    editDepartment: "Departamentni tahrirlash",
    addPosition: "Yangi lavozim",
    editPosition: "Lavozimni tahrirlash",
    deleteTitle: "O'chirishni tasdiqlang",
    deleteConfirm: "Ushbu yozuvni o'chirmoqchimisiz? Bu amalni bekor qilib bo'lmaydi.",
    createSuccess: "Yozuv qo'shildi",
    updateSuccess: "Yozuv yangilandi",
    deleteSuccess: "Yozuv o'chirildi",
    mutationError: "Amalni bajarishda xatolik yuz berdi",
  },
  reports: {
    pageTitle: "Hisobotlar",
    pageSubtitle: "Xodim yoki departament bo'yicha davomat hisoboti",
    modeEmployee: "Xodim bo'yicha",
    modeDepartment: "Departament bo'yicha",
    employeeLabel: "Xodim",
    employeePlaceholder: "Xodimni qidiring va tanlang",
    departmentLabel: "Departament",
    departmentPlaceholder: "Departamentni qidiring va tanlang",
    fromLabel: "Boshlanish sanasi",
    toLabel: "Tugash sanasi",
    fromPlaceholder: "Sanani tanlang",
    toPlaceholder: "Sanani tanlang",
    download: "Hisobotni yuklab olish",
    downloading: "Hisobot tayyorlanmoqda...",
    downloadError: "Hisobotni yuklab olishda xatolik yuz berdi",
    downloadSuccess: "Hisobot yuklab olindi",
    selectTargetFirst: "Avval xodim yoki departamentni tanlang",
    selectDatesFirst: "Sanalar oralig'ini tanlang",
    invalidRange: "Boshlanish sanasi tugash sanasidan keyin bo'lishi mumkin emas",
    previewTitle: "Hisobot ko'rinishi",
    columnEmployee: "Xodim",
    columnDate: "Sana",
    columnArrival: "Kelgan vaqti",
    columnDeparture: "Ketgan vaqti",
    columnDuration: "Davomiyligi",
    columnAddress: "Manzil",
    previewEmpty: "Hisobotni ko'rish uchun filtrlarni tanlang",
    previewEmptyHint: "Xodim yoki departamentni tanlab, sanalar oralig'ini belgilang",
    previewNoData: "Bu davr uchun ma'lumot topilmadi.",
    previewLoading: "Hisobot ma'lumotlari yuklanmoqda...",
    previewError: "Hisobot ma'lumotlarini yuklashda xatolik yuz berdi",
    previewUnavailable:
      "Oldindan ko'rish ma'lumotlari mavjud emas. Faqat Excel faylini yuklab olish mumkin.",
    previewPartial:
      "Tanlangan oraliq katta bo'lgani uchun oldindan ko'rish qisman ko'rsatilmoqda. To'liq ma'lumot Excel faylida.",
    stillHere: "Hozirgacha shu yerda",
    addressUnknown: "Manzil aniqlanmagan",
    openOnMap: "Xaritada ochish",
  },
  map: {
    loadError: "Xarita yuklanmadi",
  },
  common: {
    minutes: "daqiqa",
    hours: "soat",
    close: "Yopish",
    retry: "Qayta urinish",
    loading: "Yuklanmoqda...",
    save: "Saqlash",
    cancel: "Bekor qilish",
    confirm: "Tasdiqlash",
    yes: "Ha",
    no: "Yo'q",
    all: "Barchasi",
    noData: "Ma'lumot yo'q",
    total: "Jami",
    error: "Xatolik yuz berdi",
  },
} as const;
